/* to publish npm */
import './style.css'
import './img/b1.png';
import './img/b2.png';
import './img/b3.png';
import './img/b4.png';
import './img/b5.png';
import './img/b6.png';
import './img/b7.png';
import './img/b10.png';
import './img/b11.png';
import './img/b12.png';
import './img/c1.png';
import './img/c2.png';
import './img/c3.png';
import './img/c4.png';
import './img/c5.png';
import './img/c6.png';
import './img/c7.png';
import './img/c10.png';
import './img/c11.png';
import './img/c12.png';
import './img/e1.png';
import './img/e2.png';
import './img/e3.png';
import './img/e4.png';
import './img/e5.png';
import './img/e6.png';
import './img/e7.png';
import './img/e10.png';
import './img/e11.png';
import './img/e12.png';
import './img/icono.png';
import './img/licencia.png';
import './img/o1.png';
import './img/o2.png';
import './img/o3.png';
import './img/o4.png';
import './img/o5.png';
import './img/o6.png';
import './img/o7.png';
import './img/o10.png';
import './img/o11.png';
import './img/o12.png';
import './img/portada.png';
import './img/r0.png';
import './img/wallpaper.jpeg';
import Card from './clases/Card';
import Deck from './clases/Deck';
import Hand from './clases/Hand';

module.exports = Card;
module.exports = Deck;
module.exports = Hand;